"""create user table

Revision ID: 81933c613141
Revises: 33eed165fa05
Create Date: 2025-05-05 18:18:32.141183

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81933c613141"
down_revision: Union[str, None] = "33eed165fa05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rooms", "rating", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rooms", "rating", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
